tests: include the test for the tests
Some implementations send an error message and at the same time
will close the connection. Locally this will cause a reading from
a closed socket.

However, ldk now has a different life cycle for the connection,
and we should receive the error message before.

```
 lnprototest.errors.EventError: `Peer did not disconnect` on event [{"event": "ExpectDisconnect", "file": "test_bolt2-01-open_channel.py", "pos": "345"},]
=========================== short test summary info ============================
FAILED ../lnprototest/tests/test_bolt2-01-open_channel.py::test_open_channel_opener_side_wrong_announcement_signatures
============= 1 failed, 29 passed, 17 skipped in 96.15s (0:01:36) ==============
```

Link: https://github.com/rustyrussell/lnprototest/issues/134
Reported-by: @Psycho-Pirate
Signed-off-by: Vincenzo Palazzo <vincenzopalazzodev@gmail.com>