fix: pass the timeout when we are waiting a node to start
Thsi fix a bug that was reported with slower machine
the core lightning is not fast enought to start and
so it fails.

This PR allow to pass a custom timeout to the wait_for function.

```
self = <pyln.client.lightning.UnixSocket object at 0x7ff95de096c0>

    def connect(self) -> None:
        try:
            self.sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
>           self.sock.connect(str(self.path))
E           FileNotFoundError: [Errno 2] No such file or directory

../../../../anaconda3/envs/lnpro/lib/python3.10/site-packages/pyln/client/lightning.py:234: FileNotFoundError

------------------------------ Captured log call -------------------------------
ERROR    root:clightning.py:441 Short read reading the message length: 18 != 0
ERROR    root:clightning.py:441 Short read reading the message length: 18 != 0
=========================== short test summary info ============================
FAILED tests/test_bolt1-01-init.py::test_init_fail_ask_for_option_data_loss_protect - FileNotFoundError: [Errno 2] No such file or directory
```

Link: https://discord.com/channels/899980449231814676/941465665540325397/1112049895008899173
Signed-off-by: Vincenzo Palazzo <vincenzopalazzodev@gmail.com>